name: CI/CD Pipeline

on:
  push:
    branches:
      - cicd-pipieline
  pull_request:
    branches:
      - cicd-pipielne

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Run tests
      run: npm test

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract commit hash
      id: vars
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bankme:${{ env.COMMIT_HASH }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Set up doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Authenticate kubectl with DigitalOcean
      run: doctl kubernetes cluster kubeconfig save bankme-k8s

    - name: Update API Deployment YAML with new image
      run: |
        sed -i 's|image: .*$|image: '${{ secrets.DOCKER_USERNAME }}/bankme:${{ env.COMMIT_HASH }}'|' k8s/api/deployment.yml

    - name: Apply API Deployment
      run: kubectl apply -f bankme-backend/k8s/api/deployment.yml
